#!/bin/bash

set -euo pipefail

PLUGIN_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/.."
MAX_SIZE=1024 # in KB

echo "--- :junit: Download the junits"

ARTIFACTS_DIR="$(pwd)/$(mktemp -d "nightwatch-slack-notification-plugin-artifacts-tmp.XXXXXXXXXX")"

function cleanup {
  rm -rf "${ARTIFACTS_DIR}"
}

trap cleanup EXIT

echo "$PLUGIN_DIR"
cd "$PLUGIN_DIR"

buildkite-agent artifact download \
  "${BUILDKITE_PLUGIN_NIGHTWATCH_SLACK_NOTIFICATION_ARTIFACTS}" \
  "$ARTIFACTS_DIR"

echo "--- Compile Typescript"
make build

echo "--- Send message"
echo "token: ${BUILDKITE_PLUGIN_NIGHTWATCH_SLACK_NOTIFICATION_SLACK_TOKEN}"
echo "channel: ${BUILDKITE_PLUGIN_NIGHTWATCH_SLACK_NOTIFICATION_SLACK_CHANNEL}"
make run
